server:
  port: 5050
  servlet:
    context-path: "/"
spring:
  main:
    web-application-type: servlet

  datasource:
    url: "jdbc:postgresql://db.helydawygyybigzrcmte.supabase.co:5432/postgres"
    username: "postgres"
    password: "notanotheranilist"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        default_batch_fetch_size: 500
        order_updates: true
    show-sql: false
    open-in-view: false
