server:
  port: 5050
  servlet:
    context-path: "/api/v1"
spring:
  main:
    web-application-type: servlet

  datasource:
    url : "jdbc:postgresql://db.helydawygyybigzrcmte.supabase.co:5432/postgres"
    username: "postgres"
    password: "notanotheranilist"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
