server:
  port: 3030
  servlet:
    context-path: "/api/v2"
spring:
  main:
    web-application-type: servlet
  datasource:
    url : "jdbc:postgresql://db.helydawygyybigzrcmte.supabase.co:5432/postgres"
    username: "postgres"
    password: "notanotheranilist"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
