server:
  port: 3030
  servlet:
    context-path: "/"
spring:
  main:
    web-application-type: servlet
  datasource:
    url: "jdbc:postgresql://db.helydawygyybigzrcmte.supabase.co:5432/postgres"
    username: "postgres"
    password: "notanotheranilist"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        SQL: INFO
  file:
    name: log/jam-api.log
