server:
  port: 3030
  servlet:
    context-path: "/api/v1"
spring:
  main:
    web-application-type: servlet

  datasource:
    #aws rds jamdb
#    url: "jdbc:postgresql://jamdb.c4bltlfycvom.ap-south-1.rds.amazonaws.com:5432/jamdb"
    #supabase jamdb
    url : "jdbc:postgresql://db.helydawygyybigzrcmte.supabase.co:5432/postgres"
    username: "postgres"
    password: "notanotheranilist"
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
