server:
  port: 3030
  servlet:
    context-path: "/api/v1"
spring:
  main:
    web-application-type: servlet
  datasource:
    url: "jdbc:postgresql://localhost:5432/jamdb"
    username: "postgres"
    password: "password"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
